### PR TITLE
Fix issue 31

### PR DESCRIPTION
**Pull request by gcagrici**
Make SNS ARN default for owner notification under krux.starport.notification.sns_owner

### CODE REVIEW

**Comment by talbright** [comment]
@sushengloong this should fix the issue you ran into last night and I hit this AM.

**Comment by realstraw** [comment]
@gcagrici let's make sure to have more useful commit title during merge, and do some clean up for the commit message, these will be automatically put into the releases, they would look confusing.

**Comment by sushengloong** [comment]
@talbright - yes, `bin/submit.sh` is working for me now! Can you try again?

@gcagrici - thanks!

**Comment by talbright** [comment]
@sushengloong I verified it on my side as well, looks good.

**Pull request merged**
